name: Github-API-Test
on:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    runs-on : ubuntu-latest
    steps:
      - name: Get Commit URLs
        run: |
          time1="test"
          echo $time1
