name: Github-API-Test
on:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    runs-on : ubuntu-latest
    steps:
      - name: Get Commit URLs
        run: |
          (curl -G -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/prateekarora121/central-github-action/actions/workflows/workWithGithubRepos.yml/runs -d "status=success" ) > output.txt
          cat output.txt
          output.txt | jq -r ".workflow_runs[].created_at | sort | tail -n 1" 