name: Github-API-Test
on: workflow_dispatch
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    runs-on : ubuntu-latest
    steps:
      - name: Get Commit URLs
        run: |
          sudo apt update
          sudo apt install -y jq
          jq --version
