name: Github API Test
on:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    runs-on : windows-latest
    steps:
      - name: Get Commit URLs
        run: |
          (curl -o output.json  -G -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://github.com/prateekarora121/central-github-action/actions/workflows/workWithGithubRepos.yml/runs) 
          cat output.json