name: Github API Test
on: workflow_dispatch

defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    runs-on : windows-latest
    steps:
      - name: Get Commit URLs
        run: |
          LastPassTime=$(curl -G -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://github.com/prateekarora121/medicheck/actions/runs -d "status=success")  
          echo $LastPassTime